name: Rollback Release
  if: success()
  uses: author/action-rollback@stable
  with:
    # Using a known release ID
    release_id: ${{ steps.create_release.id }}
    # Using a tag name
    tag: 'v1.0.1'
    #  If the release does not exist but the tag does, setting this to true will remove the tag.
    delete_orphan_tag: true
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}